version: '3'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Volumes
volumes:
  # Postgres data volume
  guilda-postgres_data:
    driver: local

# IaC
services:

  # Elixir
  guilda-elixir:
    # https://hub.docker.com/r/bitwalker/alpine-elixir-phoenix/tags
    # waiting for 1.11 tag
    image: bitwalker/alpine-elixir-phoenix:latest
    container_name: guilda-elixir
    networks:
      - internal
    # /opt/app is the WORKING_DIR of the image "bitwalker/alpine-elixir-phoenix"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    ports:
      - 4001:4001
    # run bash file to start container
    command: bash /opt/app/docker-compose.sh
    depends_on:
      - "guilda-database"
    env_file:
      - .env.dev
  # Database
  guilda-database:
    image: postgis/postgis:14-3.2
    container_name: guilda-database
    networks:
      - internal
    volumes:
      - .:/var/www/app
      - guilda-postgres_data:/var/lib/postgresql/data
    working_dir: /var/www/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guilda_dev
    ports:
      - 5433:5432
