volumes:
  guilda-postgres-data:
    external: true

services:
  guilda-elixir:
    image: registry.loworbitlabs.com/guilda-elixir:latest
    restart: always
    container_name: guilda-elixir
    ports:
      - 4001:4000
    depends_on:
      - "guilda-database"
    env_file:
      - .env.prod
  # Database
  guilda-database:
    restart: always
    image: postgis/postgis:14-3.2
    container_name: guilda-database
    volumes:
      - guilda-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guilda_prod
    ports:
      - 5434:5432
networks:
  default:
    name: firefly-network
    external: true